spring:
  application:
    name: trip-service

  datasource:
    url: jdbc:h2:mem:tripdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-ui

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true

management:
  endpoint:
    health:
      enabled: true